#version: '3.8'

services:
  # Redis
  redis:
    image: redis:latest
    container_name: short-url-redis
    ports:
      - "6379:6379"
    volumes:
      - ./volumes/redis/data:/data
    restart: unless-stopped
    command: redis-server --requirepass "root"

  # MySQL数据库
  mysql:
    image: mysql:8.0
    container_name: short-url-mysql
    ports:
      - "3306:3306"
    volumes:
      - ./volumes/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: short_url
      MYSQL_USER: short_url_user
      MYSQL_PASSWORD: root
    restart: unless-stopped

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: short-url-zk
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - ./volumes/zookeeper/data:/var/lib/zookeeper/data
      - ./volumes/zookeeper/log:/var/lib/zookeeper/log
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: short-url-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # 容器内连接地址：kafka:9093，容器外连接地址：localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9093,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - ./volumes/kafka/data:/var/lib/kafka/data

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    container_name: short-url-kafdrop
    depends_on:
      - kafka
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:9093"
      KAFKA_PROPERTIES_REQUEST_TIMEOUT_MS: 30000
      KAFKA_PROPERTIES_SESSION_TIMEOUT_MS: 30000
      JVM_OPTS: "-Xms32M -Xmx64M -Dkafka.admin.timeout.ms=30000"
      SERVER_SERVLET_CONTEXTPATH: "/"

  prometheus:
    image: prom/prometheus:latest
    container_name: short-url-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./volumes/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-remote-write-receiver'
      - '--enable-feature=exemplar-storage'
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
  grafana:
    image: grafana/grafana:latest
    container_name: short-url-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    restart: unless-stopped

  generate-service:
    image: generate-service:latest
    container_name: generate-service
    depends_on:
      - mysql
      - redis
      - kafka
    ports:
      - "8080:8080"
    volumes:
      - ./volumes/generate-service/configs:/app/configs
      - ./volumes/generate-service/data:/app/data

  redirect-service:
    image: redirect-service:latest
    container_name: redirect-service
    depends_on:
      - redis
      - kafka
    ports:
      - "6060:6060"
    volumes:
      - ./volumes/redirect-service/configs:/app/configs
      - ./volumes/redirect-service/data:/app/data

  statistics-service:
    image: statistics-service:latest
    container_name: statistics-service
    depends_on:
      - mysql
      - kafka
    ports:
      - "5050:5050"
    volumes:
      - ./volumes/statistics-service/configs:/app/configs
      - ./volumes/statistics-service/data:/app/data

