server:
  port: 5050
  host: "localhost"
  mode: "debug"

# 日志配置
log:
  level: "debug"
  file_path: "./logs/app.dev.log"
  max_size: 50
  max_backups: 5
  max_age: 7
  compress: false

mysql:
  dsn: "appuser:apppass@tcp(localhost:3306)/short_url?charset=utf8mb4&parseTime=True&loc=Local"
  max_idle_conns: 5
  max_open_conns: 20
  log_level: 4

kafka:
  brokers:
    - "localhost:9092"
  client_id: "statistics-service"   # 客户端标识
  version: "2.8.1"
  interval: 5
  groups:
    - id: "record-detail"
      topics:
        - "short-link-click-events"
      fetch_max_bytes: 1048576
      auto_commit: true
      auto_commit_interval: 3600
      auto_offset: "earliest"
      session_timeout: 30s
    - id: "record-total"
      topics:
        - "short-link-click-events"
      fetch_max_bytes: 1048576
      auto_commit: true
      auto_commit_interval: 3600
      auto_offset: "earliest"
      session_timeout: 30s
      buffer_size: 1000

id_generator:
  type: "sonyflake"
  sonyflake:
    node_id: 1